---
name: CI

on:
  pull_request:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install LaTeX dependencies
        run: |
          sudo apt-get install -f -y texlive-latex-extra latexmk

      - name: Setup Python
        uses: actions/setup-python@v1

      - name: Install Sphinx
        run: |
          pip install --user --upgrade --upgrade-strategy eager sphinx sphinx-rtd-theme restructuredtext_lint pygments

      - name: Build web documentation
        run: |
          make html

      - name: Build PDF documentation
        run: |
          make latexpdf

      - name: Build EPUB documentation
        run: |
          make epub
